services:
  rover:
    build:
      context: ..
      dockerfile: ./Dockerfile
    image: roverflake2:dev
    working_dir: /RoverFlake2
    tty: true
    stdin_open: true
    volumes:
      - roverflake_workspace:/RoverFlake2
    environment:
      DISPLAY: host.docker.internal:0
      ROVERFLAKE_ROOT: /RoverFlake2
      ROVERCLI_FORCE_SETUP: "${ROVERCLI_FORCE_SETUP:-}"

volumes:
  roverflake_workspace:
