#!/bin/bash
set -e

# Load the environment generated by `rovercli setup` for interactive and
# non-interactive container commands alike.
if [ -f "$HOME/.roverrc" ]; then
  source "$HOME/.roverrc"
fi

# source system ros2
if [ -f "/opt/ros/jazzy/setup.bash" ]; then
  source /opt/ros/jazzy/setup.bash
fi

# build
if [ ! -f "$ROVERFLAKE_ROOT/install/setup.bash" ]; then
  build_jobs="${ROVER_BUILD_JOBS:-1}"
  export MAKEFLAGS="-j${build_jobs}"
  export CMAKE_BUILD_PARALLEL_LEVEL="$build_jobs"
  echo "No install/setup.bash found, running colcon build with ${build_jobs} job(s)..."
  if ! colcon build --parallel-workers "$build_jobs"; then
    echo "WARNING: initial colcon build failed. Container stays up so you can debug." >&2
    if [ ! -f "$ROVERFLAKE_ROOT/src/external_pkgs/moteus/CMakeLists.txt" ]; then
      echo "HINT: git submodules look uninitialized. On the host run: git submodule update --init --recursive" >&2
    fi
  fi
fi

# Source workspace overlay
if [ -f "$ROVERFLAKE_ROOT/install/setup.bash" ]; then
  source "$ROVERFLAKE_ROOT/install/setup.bash"
fi

exec "$@"
