# List of base APT packages required for RoverFlake
pkgs_start:
  - curl
  - git
  - btop
  - tmux
  - libgtkmm-3.0-dev # GUI Package
  - libsfml-dev
  - libgpiod-dev

pkgs_after_ros:
  - python3-rosdep
  - ros-${ROS_DISTRO}-rmw-cyclonedds-cpp